### ISSUE TITLE
Issue when running streamlit.py

### ISSUE THREAD

**Issue by vivekuppal** [hwchase17/conversational-retrieval-agent#1]
I am getting the following error when executing streamlit.py

```
(convo) C:\git\conversational-retrieval-agent>streamlit run streamlit.py
Traceback (most recent call last):
  File "C:\git\conversational-retrieval-agent\streamlit.py", line 1, in <module>
    import streamlit as st
  File "C:\git\conversational-retrieval-agent\streamlit.py", line 21, in <module>
    st.set_page_config(
    ^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'streamlit' has no attribute 'set_page_config' (most likely due to a circular import)
```

I have a PR to remedy the issue, please provide access to create a PR in this repo

**Comment by David-GERARD** [comment]
I have had the same issue when running the https://github.com/streamlit/streamlit-app-action.
